# Make sure the EventCatalog can build OK
name: Tests

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Verify Build
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Installation
        run: npm i
      - name: Tests
        run: npm run test