# Make sure the EventCatalog can build OK
name: Verify Build

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Verify Build
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Installation
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack

      - name: Rename package artifact
        run: mv *.tgz package.tgz # Rename to a consistent name

      - name: Upload package artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: package-artifact
          path: package.tgz

  test-bin:
    needs: build
    strategy:
      matrix:
        package-manager: [pnpm, npm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install package manager
        if: matrix.package-manager == 'pnpm'
        run: npm install -g pnpm

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: package-artifact

      - name: Install package in ./examples/default/
        working-directory: ./examples/default/
        run: |
          # Install the packed package in the examples directory
          if [ "${{ matrix.package-manager }}" = "yarn" ]; then
            yarn add @eventcalog/core@file:../../package.tgz
          else 
            ${{ matrix.package-manager }} install ../../package.tgz
          fi

      - name: Build event catalog in ./examples/default/
        working-directory: ./examples/default/
        env:
          NODE_ENV: CI # Prevent raise event to analytics
        run: ${{ matrix.package-manager }} run build
