# Make sure the EventCatalog can build OK
# Both on Windows and Linux
name: Verify Build

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  verify-build:
    name: Verify Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Installation
        run: pnpm i
      - name: Test
        run: pnpm run test:ci
      - name: Build cli
        run: pnpm --filter @eventcatalog/core run build
      - name: Build EventCatalog
        run: pnpm --filter @example/default exec eventcatalog build
